run:
  tests: true
  timeout: 5m

linters:
  enable:
    - gofmt
    - govet
    - errcheck
    - unused
    - gosimple
    - staticcheck
    - ineffassign
    - typecheck
    - gosec
    - gocritic
    - misspell
    - bodyclose
    - whitespace
    - thelper
    - goconst
    - noctx
    - prealloc

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true
  gosec:
    excludes:
      - G115
      - G204
  gocritic:
    enabled-tags:
      - style
      - performance
    disabled-checks:
      - ifElseChain
      - hugeParam
      - unnamedResult
      - whyNoLint
      - appendAssign
      - paramTypeCombine
      - typeAssertChain
      - exitAfterDefer
      - octalLiteral
      - httpNoBody
      - stringXbytes
      - nestingReduce
      - appendCombine
      - rangeValCopy
      - builtinShadow
  prealloc:
    simple: true
    range-loops: true
    for-loops: true

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude-rules:
    - linters: [staticcheck]
      text: "SA1019:"
    - linters: [staticcheck]
      text: "SA1029:"
    - linters: [staticcheck]
      text: "SA5011"
    - linters: [gosec]
      text: "G404:"
    - linters: [gosec]
      text: "G304:"
    - linters: [gosec]
      text: "G306:"
    - linters: [gosec]
      text: "G301:"
    - linters: [gosec]
      text: "G302:"
    - linters: [gosec]
      text: "G107:"
    - linters: [gosec]
      text: "G112:"
    - linters: [gosec]
      text: "G402:"
    - linters: [gosec]
      text: "G114:"
    - linters: [gosec]
      text: "G104:"
    - linters: [unused]
      text: "."
    - linters: [goconst]
      text: "."
    - linters: [prealloc]
      text: "."
    - linters: [thelper]
      text: "."
    - linters: [whitespace]
      text: "."
    - linters: [errcheck]
      text: "."
    - linters: [noctx]
      text: "."
    - linters: [bodyclose]
      text: "."
    - linters: [gosimple]
      text: "."
