run:
  tests: true

linters:
  enable:
    - gofmt
    - govet
    - errcheck
    - unused
    - gosimple
    - staticcheck
    - ineffassign
    - typecheck

issues:
  exclude-use-default: false
  exclude:
    - "Error return value of.*is not checked"
